#### 2023-2 DSL 정규세션 과제
##### ML/DL을 위한 수학 1, 2
 - 작성자 : 서연우, 김서진
 - 과제 제출 기한 : 2023.07.22 (토) 11:59
 ---


- 이름 :
- 기수 :

##### Q1. 아래 행렬 A를 보고 물음에 답하세요. (과정은 수기로 작성 후 pdf로 업로드해주세요.)

In [1]:
import numpy as np

A = np.array([[1, 0, 1],
              [0, 2, 3],
              [0, 0, 3]])

print(A)

[[1 0 1]
 [0 2 3]
 [0 0 3]]


(1) 다음 행렬의 determinant를 구하고, 기하학적으로 어떤 의미를 갖는지 서술하시오.

(2) A의 eigenvalue, eigenvector를 각각 찾고 각각의 의미를 서술하시오.

##### Q2. Matrix B 에 대해 diagonalization을 시행하고 그 과정을 서술하시오.

In [2]:
B = np.array([[0, 0, 0],
              [0, 0, 0],
              [3, 0, 1]])

print(B)

[[0 0 0]
 [0 0 0]
 [3 0 1]]


##### Q3. 아래 문제를 읽고 해결하시오.
메일 시스템에서 스팸 필터링을 담당하는 베이즈 필터가 있습니다. 이 필터는 메일이 스팸일 확률을 계산하기 위해 베이즈 정리를 사용합니다. 베이즈 필터는 다음의 약률을 알고 있습니다:
- 메일 시스템에 도착하는 메일 중 스팸 메일의 비율(p(Spam))은 20%입니다.
- 스팸 메일 중에서 '당첨'이라는 단어를 포항하는 비율(P('당첨' | Spam))은 50% 입니다.
- 스팸이 아닌 정상 메일 중에서 '당첨'이라는 단어를 포함하는 비율(P('당첨' | Not Spam))은 1%입니다.

어느 날, 메일 시스템에 '당첨'이라는 단어를 포함하는 메일이 도착했습니다. 이 메일이 스팸일 확률을 베이즈 정리를 이용하여 계산하십시오

##### Q4. 야구 경기에서 타자가 스윙을 치는 경우, 그 결과는 안타와 아웃 두가지 중 하나가 될 수 있습니다. (홈런도 안타로 간주합니다.) 이 때, 타자의 스윙 결과를 예측하는 모델을 만들고자 이전 타자들의 기록을 수집했습니다. 그 결과는 hit.csv의 결과와 같습니다. 아래 3문제를 hit.csv의 결과를 바탕으로 해결해주세요. (계산 결과는 소수점 셋째자리까지 반올림하여 표현해주세요.)


(1) 스윙 결과의 분포는 어떤 분포의 일종입니다. 이 분포가 어떤 분포인지 말하고, 해당 분포의 엔트로피를 코드로 작성해 계산하여 그 값을 plot으로 그려주세요. 
###간단하게, 앞면과 뒷면이 나올 확률이 같은 동전을 던졌을 때, 앞면이 나올 확률에 대한 엔트로피를 plot으로 그려주세요.

In [ ]:
# 엔트로피를 코드로 계산하고 이를 시각화하기

(2) hit.csv의 엔트로피를 코드를 사용하지 말고 손으로 계산하세요.(과정은 수기로 작성 후 pdf로 업로드해주세요.)

In [3]:
import pandas as pd
# 디렉토리 설정하여 데이터 로드
hit = pd.read_csv('/Users/gimseojin/Desktop/2023-2/DSL/hit.csv', index_col=0)
hit

스윙 결과
타자      
1    Hit
2    Hit
3    Out
4    Hit
5    Out
6    Hit
7    Hit
8    Out
9    Out
10   Hit
11   Hit
12   Hit
13   Out
14   Out
15   Hit

(3) 계산하던 중, 다른 팀의 타자 기록을 얻게 되었습니다. 이 기록을 hit_other.csv에 저장해두었습니다. 첫번째 팀에 대해, 첫번째 팀과 두번째 팀의 스윙 결과 데이터 분포의 차이를 손으로 계산하세요. (과정은 수기로 작성 후 pdf로 업로드해주세요.)

In [14]:
# 디렉토리 설정하여 데이터 로드
hit_other = pd.read_csv('/Users/gimseojin/Desktop/2023-2/DSL/hit_other.csv', index_col=0)
hit_other

스윙 결과
타자      
1    Out
2    Hit
3    Out
4    Out
5    Out
6    Hit
7    Hit
8    Out
9    Out
10   Out
11   Hit
12   Out
13   Out
14   Out
15   Out

##### Q4. Logistic Regression의 Convex optimization 과정을 서술해주세요. (과정은 수기로 작성 후 pdf로 업로드해주세요.)